"""
Report generation module.
Creates research reports in multiple formats from repository analysis.
"""

import json
from typing import Dict, List, Any
from datetime import datetime
import markdown
import pdfkit


class ReportGenerator:
    """Generate research reports from repository analysis."""

    def __init__(self):
        """Initialize report generator."""
        pass

    def generate_markdown_report(self, analysis: Dict[str, Any], comparison: Dict[str, Any] = None) -> str:
        """
        Generate a Markdown research report.

        Args:
            analysis: Repository analysis data
            comparison: Optional comparative analysis data

        Returns:
            Markdown report string
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        repo_name = analysis["basic_info"]["full_name"]

        report = f"""# GitHub Repository Research Report

**Repository:** {repo_name}
**Generated:** {timestamp}
**Report ID:** {analysis["basic_info"]["owner"]}-{analysis["basic_info"]["repo"]}-{datetime.now().strftime("%Y%m%d")}

---

## Executive Summary

{self._generate_executive_summary(analysis)}

## Repository Overview

- **Description:** {analysis["basic_info"]["description"] or "No description provided"}
- **URL:** {analysis["basic_info"]["url"]}
- **Created:** {analysis["basic_info"]["created_at"]}
- **Last Updated:** {analysis["basic_info"]["updated_at"]}
- **Age:** {analysis["basic_info"]["age_days"]} days
- **Size:** {analysis["basic_info"]["size_kb"]:,} KB

## Key Metrics

### Popularity Metrics
- **Stars:** {analysis["metrics"]["stars"]:,}
- **Forks:** {analysis["metrics"]["forks"]:,}
- **Watchers:** {analysis["metrics"]["watchers"]:,}
- **Stars per Day:** {analysis["metrics"]["stars_per_day"]:.2f}
- **Stars per Fork:** {analysis["metrics"]["stars_per_fork"]:.2f}
- **Popularity Score:** {analysis["popularity_score"]}/100

### Activity Metrics
- **Open Issues:** {analysis["metrics"]["open_issues"]:,}
- **Contributors:** {analysis["metrics"]["contributors"]:,}
- **Recent Commits (30 days):** {analysis["activity"]["commit_count"]:,}
- **Commits per Day:** {analysis["activity"]["commits_per_day"]:.2f}
- **Health Score:** {analysis["health_score"]}/100

## Growth Analysis

{self._generate_growth_analysis(analysis)}

## Language Distribution

{self._generate_language_distribution(analysis["languages"])}

## Insights & Recommendations

{self._generate_insights(analysis)}

## Detailed Metrics

{self._generate_detailed_metrics(analysis)}

---

*Report generated by GitHub Stars Research Analyzer*
*Data source: GitHub API*
"""

        if comparison:
            report += f"\n\n## Comparative Analysis\n\n{self._generate_comparison_section(comparison)}"

        return report

    def _generate_executive_summary(self, analysis: Dict[str, Any]) -> str:
        """Generate executive summary section."""
        repo_name = analysis["basic_info"]["full_name"]
        stars = analysis["metrics"]["stars"]
        popularity_score = analysis["popularity_score"]
        health_score = analysis["health_score"]

        if popularity_score >= 80:
            popularity_desc = "highly popular"
        elif popularity_score >= 60:
            popularity_desc = "moderately popular"
        elif popularity_score >= 40:
            popularity_desc = "somewhat popular"
        else:
            popularity_desc = "less popular"

        if health_score >= 80:
            health_desc = "excellent health"
        elif health_score >= 60:
            health_desc = "good health"
        elif health_score >= 40:
            health_desc = "fair health"
        else:
            health_desc = "poor health"

        return f"""
The repository **{repo_name}** shows {popularity_desc} with {stars:,} stars and demonstrates {health_desc}.
This analysis provides insights into growth patterns, community engagement, and project sustainability.
"""

    def _generate_growth_analysis(self, analysis: Dict[str, Any]) -> str:
        """Generate growth analysis section."""
        stars = analysis["metrics"]["stars"]
        stars_per_day = analysis["metrics"]["stars_per_day"]
        age_days = analysis["basic_info"]["age_days"]

        if age_days > 0:
            daily_growth_rate = (stars_per_day / stars) * 100 if stars > 0 else 0
            weekly_growth = daily_growth_rate * 7
            monthly_growth = daily_growth_rate * 30
        else:
            daily_growth_rate = weekly_growth = monthly_growth = 0

        return f"""
### Growth Metrics
- **Daily Star Growth:** {stars_per_day:.2f} stars/day
- **Daily Growth Rate:** {daily_growth_rate:.4f}%
- **Weekly Growth Rate:** {weekly_growth:.4f}%
- **Monthly Growth Rate:** {monthly_growth:.4f}%

### Projections (Based on Current Rate)
- **30-day Projection:** {stars + (stars_per_day * 30):.0f} stars
- **90-day Projection:** {stars + (stars_per_day * 90):.0f} stars
- **180-day Projection:** {stars + (stars_per_day * 180):.0f} stars
"""

    def _generate_language_distribution(self, languages: Dict[str, int]) -> str:
        """Generate language distribution section."""
        if not languages:
            return "No language data available."

        total_bytes = sum(languages.values())
        language_lines = []

        for lang, bytes_count in sorted(languages.items(), key=lambda x: x[1], reverse=True):
            percentage = (bytes_count / total_bytes) * 100
            language_lines.append(f"- **{lang}:** {percentage:.1f}% ({bytes_count:,} bytes)")

        return "\n".join(language_lines)

    def _generate_insights(self, analysis: Dict[str, Any]) -> str:
        """Generate insights and recommendations section."""
        insights = []

        # Popularity insights
        popularity_score = analysis["popularity_score"]
        if popularity_score >= 80:
            insights.append("✅ **High Popularity:** Repository is trending well with strong community engagement.")
        elif popularity_score >= 60:
            insights.append("📈 **Growing Popularity:** Repository shows steady growth and good community interest.")
        else:
            insights.append("📊 **Development Opportunity:** Consider increasing visibility through documentation and outreach.")

        # Health insights
        health_score = analysis["health_score"]
        if health_score >= 80:
            insights.append("✅ **Excellent Health:** Active development with good issue management.")
        elif health_score >= 60:
            insights.append("🔄 **Good Health:** Regular updates and reasonable issue resolution.")
        else:
            insights.append("⚠️ **Needs Attention:** Consider addressing open issues and increasing development activity.")

        # Growth insights
        stars_per_day = analysis["metrics"]["stars_per_day"]
        if stars_per_day >= 10:
            insights.append("🚀 **Rapid Growth:** Exceptional star growth rate indicates strong market fit.")
        elif stars_per_day >= 1:
            insights.append("📈 **Steady Growth:** Consistent growth suggests sustainable popularity.")
        else:
            insights.append("📊 **Slow Growth:** Consider strategies to increase repository visibility.")

        # Activity insights
        commits_per_day = analysis["activity"]["commits_per_day"]
        if commits_per_day >= 2:
            insights.append("💻 **High Activity:** Very active development with frequent updates.")
        elif commits_per_day >= 0.5:
            insights.append("🔄 **Moderate Activity:** Regular development activity.")
        else:
            insights.append("⏸️ **Low Activity:** Consider increasing development frequency or community contributions.")

        return "\n\n".join(insights)

    def _generate_detailed_metrics(self, analysis: Dict[str, Any]) -> str:
        """Generate detailed metrics section."""
        metrics = analysis["metrics"]
        activity = analysis["activity"]

        return f"""
### Detailed Metrics Table

| Metric | Value | Description |
|--------|-------|-------------|
| **Stars** | {metrics["stars"]:,} | Total stargazers |
| **Forks** | {metrics["forks"]:,} | Total repository forks |
| **Watchers** | {metrics["watchers"]:,} | Users watching repository |
| **Open Issues** | {metrics["open_issues"]:,} | Currently open issues |
| **Contributors** | {metrics["contributors"]:,} | Unique contributors |
| **Stars per Fork** | {metrics["stars_per_fork"]:.2f} | Popularity relative to forks |
| **Stars per Watcher** | {metrics["stars_per_watcher"]:.2f} | Popularity relative to watchers |
| **Issues per Star** | {metrics["issues_per_star"]:.4f} | Issue density |
| **Recent Commits** | {activity["commit_count"]:,} | Commits in last {activity["days_active"]} days |
| **Commits per Day** | {activity["commits_per_day"]:.2f} | Average daily commits |
"""

    def _generate_comparison_section(self, comparison: Dict[str, Any]) -> str:
        """Generate comparison section."""
        summary = comparison["summary"]

        section = f"""
### Comparison Summary
- **Total Repositories Compared:** {summary["total_repositories"]}
- **Total Stars:** {summary["total_stars"]:,}
- **Total Forks:** {summary["total_forks"]:,}
- **Average Stars:** {summary["average_stars"]:.1f}
- **Average Forks:** {summary["average_forks"]:.1f}
- **Average Popularity Score:** {summary["average_popularity"]:.1f}/100
- **Average Health Score:** {summary["average_health"]:.1f}/100

### Top Repositories by Stars
"""

        for i, repo in enumerate(comparison["rankings"]["by_stars"][:5], 1):
            section += f"{i}. **{repo['basic_info']['full_name']}** - {repo['metrics']['stars']:,} stars\n"

        section += "\n### Top Repositories by Popularity Score\n"

        for i, repo in enumerate(comparison["rankings"]["by_popularity"][:5], 1):
            section += f"{i}. **{repo['basic_info']['full_name']}** - {repo['popularity_score']}/100\n"

        return section

    def generate_json_report(self, analysis: Dict[str, Any], comparison: Dict[str, Any] = None) -> str:
        """
        Generate a JSON research report.

        Args:
            analysis: Repository analysis data
            comparison: Optional comparative analysis data

        Returns:
            JSON report string
        """
        report = {
            "metadata": {
                "generated_at": datetime.now().isoformat(),
                "report_type": "github_repository_analysis",
                "repository": analysis["basic_info"]["full_name"]
            },
            "analysis": analysis,
            "summary": {
                "executive_summary": self._generate_executive_summary(analysis),
                "key_metrics": {
                    "stars": analysis["metrics"]["stars"],
                    "forks": analysis["metrics"]["forks"],
                    "popularity_score": analysis["popularity_score"],
                    "health_score": analysis["health_score"]
                }
            }
        }

        if comparison:
            report["comparison"] = comparison

        return json.dumps(report, indent=2)

    def generate_pdf_report(self, analysis: Dict[str, Any], output_path: str, comparison: Dict[str, Any] = None) -> bool:
        """
        Generate a PDF research report.

        Args:
            analysis: Repository analysis data
            output_path: Path to save PDF file
            comparison: Optional comparative analysis data

        Returns:
            True if successful, False otherwise
        """
        try:
            # Generate markdown first
            markdown_content = self.generate_markdown_report(analysis, comparison)

            # Convert markdown to HTML
            html_content = markdown.markdown(markdown_content)

            # Add basic styling
            styled_html = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <title>GitHub Repository Research Report</title>
                <style>
                    body {{ font-family: Arial, sans-serif; margin: 40px; }}
                    h1 {{ color: #333; border-bottom: 2px solid #0366d6; }}
                    h2 {{ color: #555; margin-top: 30px; }}
                    table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
                    th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                    th {{ background-color: #f2f2f2; }}
                    .insight {{ background-color: #f8f9fa; padding: 15px; border-left: 4px solid #0366d6; margin: 15px 0; }}
                    .timestamp {{ color: #666; font-size: 0.9em; }}
                </style>
            </head>
            <body>
                {html_content}
            </body>
            </html>
            """

            # Generate PDF
            pdfkit.from_string(styled_html, output_path)
            return True

        except Exception as e:
            print(f"Error generating PDF: {e}")
            return False